AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    777c1d51-3012-4805-b84d-08367ebbd2c7:
      size:
        width: 890
        height: 300
      position:
        x: -3
        'y': 631
      z: 0
      embeds:
        - ce1e3ad5-89e8-4b75-8bfe-0ce7ed7672dc
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
    3cd0dd39-c481-4ec2-88d6-92ba196e858b:
      size:
        width: 210
        height: 190
      position:
        x: 67
        'y': 701
      z: 1
      parent: 777c1d51-3012-4805-b84d-08367ebbd2c7
      embeds:
        - 6fa74a25-7bb9-4404-b6d6-34fbfcb08a9c
    6fa74a25-7bb9-4404-b6d6-34fbfcb08a9c:
      size:
        width: 60
        height: 60
      position:
        x: 90
        'y': 740
      z: 2
      parent: 3cd0dd39-c481-4ec2-88d6-92ba196e858b
      embeds: []
      iscontainedinside:
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
      dependson:
        - 6b1e4543-dce7-40a3-a170-a97e8059a462
    ce1e3ad5-89e8-4b75-8bfe-0ce7ed7672dc:
      size:
        width: 60
        height: 60
      position:
        x: 290.4889221191406
        'y': 650.2954711914062
      z: 1
      parent: 777c1d51-3012-4805-b84d-08367ebbd2c7
      embeds: []
      iscontainedinside:
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
    7ac31814-85f5-45a4-aed0-722a48e9bd38:
      size:
        width: 60
        height: 60
      position:
        x: -120
        'y': 570
      z: 0
      embeds: []
    1935b7b6-319e-439b-9b10-767a8a3154a8:
      source:
        id: 777c1d51-3012-4805-b84d-08367ebbd2c7
      target:
        id: 7ac31814-85f5-45a4-aed0-722a48e9bd38
      z: 0
    195d26f1-c3f9-4f39-88e9-4a2a90f263f8:
      size:
        width: 130
        height: 130
      position:
        x: 450
        'y': 790
      z: 1
      parent: 777c1d51-3012-4805-b84d-08367ebbd2c7
      embeds:
        - 6b1e4543-dce7-40a3-a170-a97e8059a462
      dependson:
        - 777c1d51-3012-4805-b84d-08367ebbd2c7
        - 3cd0dd39-c481-4ec2-88d6-92ba196e858b
    6b1e4543-dce7-40a3-a170-a97e8059a462:
      size:
        width: 60
        height: 60
      position:
        x: 491.4889221191406
        'y': 827.2954711914062
      z: 2
      parent: 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
      embeds: []
      iscontainedinside:
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
        - 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
      dependson:
        - 1935b7b6-319e-439b-9b10-767a8a3154a8
        - 7ac31814-85f5-45a4-aed0-722a48e9bd38
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/16
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 777c1d51-3012-4805-b84d-08367ebbd2c7
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3cd0dd39-c481-4ec2-88d6-92ba196e858b
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref WebServerSG
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PublicSubnet
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum install -y aws-cfn-bootstrap
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource WebServerInstance '
            - '         --configsets All '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

            - |
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource WebServerInstance '
            - '         --region '
            - !Ref 'AWS::Region'
            - ''
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6fa74a25-7bb9-4404-b6d6-34fbfcb08a9c
    DependsOn:
      - PublicRoute
  WebServerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow access from HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ce1e3ad5-89e8-4b75-8bfe-0ce7ed7672dc
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7ac31814-85f5-45a4-aed0-722a48e9bd38
  VPC2IG:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1935b7b6-319e-439b-9b10-767a8a3154a8
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 195d26f1-c3f9-4f39-88e9-4a2a90f263f8
    DependsOn:
      - VPC
      - PublicSubnet
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6b1e4543-dce7-40a3-a170-a97e8059a462
    DependsOn:
      - VPC2IG
      - InternetGateway
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: ' The IP address range that can be used to access the web server using SSH.'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0ff8a91507f77f867
      HVMG2: ami-0a584ac55a7631c0c
    us-west-2:
      HVM64: ami-a0cfeed8
      HVMG2: ami-0e09505bc235aa82d
    us-west-1:
      HVM64: ami-0bdb828fd58c52235
      HVMG2: ami-066ee5fd4a9ef77f1
    eu-west-1:
      HVM64: ami-047bb4163c506cd98
      HVMG2: ami-0a7c483d527806435
    eu-west-2:
      HVM64: ami-f976839e
      HVMG2: NOT_SUPPORTED
    eu-west-3:
      HVM64: ami-0ebc281c20e89ba4b
      HVMG2: NOT_SUPPORTED
    eu-central-1:
      HVM64: ami-0233214e13e500f77
      HVMG2: ami-06223d46a6d0661c7
    ap-northeast-1:
      HVM64: ami-06cd52961ce9f0d85
      HVMG2: ami-053cdd503598e4a9d
    ap-northeast-2:
      HVM64: ami-0a10b2721688ce9d2
      HVMG2: NOT_SUPPORTED
    ap-northeast-3:
      HVM64: ami-0d98120a9fb693f07
      HVMG2: NOT_SUPPORTED
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309
    ap-southeast-2:
      HVM64: ami-09b42976632b27e9b
      HVMG2: ami-0a9ce9fecc3d1daf8
    ap-south-1:
      HVM64: ami-0912f71e06545ad88
      HVMG2: ami-097b15e89dbdcfcf4
    us-east-2:
      HVM64: ami-0b59bfac6be064b78
      HVMG2: NOT_SUPPORTED
    ca-central-1:
      HVM64: ami-0b18956f
      HVMG2: NOT_SUPPORTED
    sa-east-1:
      HVM64: ami-07b14488da8ea02a0
      HVMG2: NOT_SUPPORTED
    cn-north-1:
      HVM64: ami-0a4eaf6c4454eda75
      HVMG2: NOT_SUPPORTED
    cn-northwest-1:
      HVM64: ami-6b6a7d09
      HVMG2: NOT_SUPPORTED
Outputs:
  URL:
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - WebServer
          - PublicIp
    Description: Newly created application URL
