AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    edef8a41-9c1d-46eb-a29f-a72f78c8446a:
      size:
        width: 2410
        height: 990
      position:
        x: -720
        'y': 390
      z: 0
      embeds:
        - 88232fe9-5945-4770-afc6-0b8ec5550b41
        - 3c74a295-8a01-4b6f-9085-3791cb237828
        - 07334a8b-ada4-4dd4-9446-03492f68ccc4
        - c6c40432-a863-4b5f-a4d8-47dda49c861c
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - bddcbbc4-e9e0-4331-8e72-1dc59078f70a
        - ddb9de6a-2c82-43e8-ada5-952a3d976548
    358d871b-95d8-4e65-a91d-72e3ac445d68:
      size:
        width: 480
        height: 310
      position:
        x: -670
        'y': 430
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds:
        - a39ba498-9fa2-43a6-acce-96b0a1d8c1ef
    8d838283-135a-4538-b69d-ace7c475514f:
      size:
        width: 540
        height: 330
      position:
        x: -50
        'y': 420
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds:
        - 7175e9ff-d7e8-4e27-88d5-7d7fdb45a267
    0809b2eb-369c-41f0-bf53-bce737b7e7ae:
      size:
        width: 450
        height: 320
      position:
        x: 610
        'y': 430
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds:
        - dfe2e52d-3954-472c-ab08-fc189412c06f
    c6c40432-a863-4b5f-a4d8-47dda49c861c:
      size:
        width: 510
        height: 310
      position:
        x: -670
        'y': 910
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds: []
    07334a8b-ada4-4dd4-9446-03492f68ccc4:
      size:
        width: 550
        height: 320
      position:
        x: -60
        'y': 900
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds: []
    3c74a295-8a01-4b6f-9085-3791cb237828:
      size:
        width: 480
        height: 330
      position:
        x: 600
        'y': 920
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds: []
    a39ba498-9fa2-43a6-acce-96b0a1d8c1ef:
      size:
        width: 60
        height: 60
      position:
        x: -290
        'y': 460
      z: 2
      parent: 358d871b-95d8-4e65-a91d-72e3ac445d68
      embeds: []
      isassociatedwith:
        - ddb9de6a-2c82-43e8-ada5-952a3d976548
      iscontainedinside:
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
      dependson:
        - 1f98040d-45ca-4703-9a6f-ad27365f092e
    7175e9ff-d7e8-4e27-88d5-7d7fdb45a267:
      size:
        width: 60
        height: 60
      position:
        x: -30
        'y': 450
      z: 2
      parent: 8d838283-135a-4538-b69d-ace7c475514f
      embeds: []
      isassociatedwith:
        - ddb9de6a-2c82-43e8-ada5-952a3d976548
      iscontainedinside:
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 8d838283-135a-4538-b69d-ace7c475514f
      dependson:
        - 1f98040d-45ca-4703-9a6f-ad27365f092e
    dfe2e52d-3954-472c-ab08-fc189412c06f:
      size:
        width: 60
        height: 60
      position:
        x: 630
        'y': 460
      z: 2
      parent: 0809b2eb-369c-41f0-bf53-bce737b7e7ae
      embeds: []
      isassociatedwith:
        - ddb9de6a-2c82-43e8-ada5-952a3d976548
      iscontainedinside:
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
      dependson:
        - 1f98040d-45ca-4703-9a6f-ad27365f092e
    ddb9de6a-2c82-43e8-ada5-952a3d976548:
      size:
        width: 60
        height: 60
      position:
        x: -150
        'y': 450
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds: []
      iscontainedinside:
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
    bddcbbc4-e9e0-4331-8e72-1dc59078f70a:
      size:
        width: 60
        height: 60
      position:
        x: -140
        'y': 830
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds: []
      iscontainedinside:
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
        - edef8a41-9c1d-46eb-a29f-a72f78c8446a
    f83697cd-122c-4f9b-9248-b6d3aef6d000:
      size:
        width: 60
        height: 60
      position:
        x: 1040
        'y': 210
      z: 0
      embeds: []
    12710065-cd43-4a73-bdeb-66f1a170730d:
      source:
        id: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      target:
        id: f83697cd-122c-4f9b-9248-b6d3aef6d000
      z: 0
    88232fe9-5945-4770-afc6-0b8ec5550b41:
      size:
        width: 410
        height: 310
      position:
        x: 1120
        'y': 450
      z: 1
      parent: edef8a41-9c1d-46eb-a29f-a72f78c8446a
      embeds:
        - 1f98040d-45ca-4703-9a6f-ad27365f092e
      dependson:
        - 0809b2eb-369c-41f0-bf53-bce737b7e7ae
        - 8d838283-135a-4538-b69d-ace7c475514f
        - 358d871b-95d8-4e65-a91d-72e3ac445d68
    1f98040d-45ca-4703-9a6f-ad27365f092e:
      size:
        width: 60
        height: 60
      position:
        x: 1152
        'y': 482
      z: 2
      parent: 88232fe9-5945-4770-afc6-0b8ec5550b41
      embeds: []
      iscontainedinside:
        - 88232fe9-5945-4770-afc6-0b8ec5550b41
        - 88232fe9-5945-4770-afc6-0b8ec5550b41
        - 88232fe9-5945-4770-afc6-0b8ec5550b41
      dependson:
        - f83697cd-122c-4f9b-9248-b6d3aef6d000
    075a6123-a058-4a65-92c5-27042810328a:
      source:
        id: 88232fe9-5945-4770-afc6-0b8ec5550b41
      target:
        id: 0809b2eb-369c-41f0-bf53-bce737b7e7ae
      z: 3
    f27b18cd-2aec-4950-9952-005c2910c775:
      source:
        id: 88232fe9-5945-4770-afc6-0b8ec5550b41
      target:
        id: 8d838283-135a-4538-b69d-ace7c475514f
      z: 4
    831e1032-57f5-4f97-a1a8-af397e018d18:
      source:
        id: 88232fe9-5945-4770-afc6-0b8ec5550b41
      target:
        id: 358d871b-95d8-4e65-a91d-72e3ac445d68
      z: 5
Resources:
  myStackVpc:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: edef8a41-9c1d-46eb-a29f-a72f78c8446a
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 358d871b-95d8-4e65-a91d-72e3ac445d68
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8d838283-135a-4538-b69d-ace7c475514f
  PublicSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0809b2eb-369c-41f0-bf53-bce737b7e7ae
  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c6c40432-a863-4b5f-a4d8-47dda49c861c
  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 07334a8b-ada4-4dd4-9446-03492f68ccc4
  PrivateSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3c74a295-8a01-4b6f-9085-3791cb237828
  MyStackWebServer1:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
        - SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref MyStackPublicSG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a39ba498-9fa2-43a6-acce-96b0a1d8c1ef
    DependsOn:
      - PublicRoute
  MyStackWebServer2:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
        - SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref MyStackPublicSG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7175e9ff-d7e8-4e27-88d5-7d7fdb45a267
    DependsOn:
      - PublicRoute
  MyStackWebServer3:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
        - SubnetId: !Ref PublicSubnet3
      SecurityGroupIds:
        - !Ref MyStackPublicSG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dfe2e52d-3954-472c-ab08-fc189412c06f
    DependsOn:
      - PublicRoute
  MyStackPublicSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref myStackVpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ddb9de6a-2c82-43e8-ada5-952a3d976548
  MyStackPrivateSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref myStackVpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bddcbbc4-e9e0-4331-8e72-1dc59078f70a
  MyStackIG:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f83697cd-122c-4f9b-9248-b6d3aef6d000
  MyStackIGAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref MyStackIG
      VpcId: !Ref myStackVpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 12710065-cd43-4a73-bdeb-66f1a170730d
  MyStackPublicRT:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 88232fe9-5945-4770-afc6-0b8ec5550b41
    DependsOn:
      - PublicSubnet3
      - PublicSubnet2
      - PublicSubnet1
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref MyStackPublicRT
      GatewayId: !Ref MyStackIG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1f98040d-45ca-4703-9a6f-ad27365f092e
    DependsOn:
      - MyStackIG
